version: 2.1
executors:
  infrastructure_container:
    docker:
      - image: aeternity/infrastructure:v2.12.4
    working_directory: /src

commands:
  setup_secrets:
    steps:
      - run:
          name: Setup environment secrets
          command: cd /infrastructure && make secrets SECRETS_OUTPUT_DIR=/secrets

  terraform_init:
    parameters:
      path:
        type: string
        default: "."
      lock_timeout:
        type: string
        default: "5m"
    steps:
      - run:
          name: Terraform init
          command: |
            envdir /secrets terraform -chdir=<< parameters.path >> init -lock-timeout=<< parameters.lock_timeout >>

  terraform_validate:
    description: Format check and validate. Requires init.
    parameters:
      path:
        type: string
        default: "."
    steps:
      - run:
          name: Terraform format check
          command: |
            terraform -chdir=<< parameters.path >> fmt -check=true -diff=true
      - run:
          name: Terraform validate
          command: |
            terraform -chdir=<< parameters.path >> validate

  terraform_plan:
    parameters:
      path:
        type: string
        default: "."
      parallelism:
        type: integer
        default: 20
      lock_timeout:
        type: string
        default: "5m"
      plans_workspace:
        type: string
        default: /tmp/plans
      out:
        type: string
        default: plan.out
    steps:
      - run:
          name: Terraform plan
          command: |
            mkdir -p $(dirname "<< parameters.out >>")
            envdir /secrets terraform -chdir=<< parameters.path >> plan \
              -lock-timeout=<< parameters.lock_timeout >> \
              -parallelism=<< parameters.parallelism >> \
              -out=<< parameters.out >> \
              -var vault_addr=${VAULT_ADDR:?} | tee terraform-plan-info

            export TERRAFORM_PLAN_INFO=`cat terraform-plan-info | grep Plan: | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g'`
            curl -sSX POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d '{
                "state": "success",
                "target_url": "'"${CIRCLE_BUILD_URL}"'",
                "description": "'"${TERRAFORM_PLAN_INFO}"'",
                "context": "terraform plan"
              }' \
              https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/statuses/${CIRCLE_SHA1} > /dev/null
      - persist_to_workspace:
          root: << parameters.path >>
          paths:
            - "*.out"

  terraform_apply:
    parameters:
      path:
        type: string
        default: "."
      out:
        type: string
        default: "plan.out"
      auto_approve:
        type: boolean
        default: false
      parallelism:
        type: integer
        default: 20
      lock_timeout:
        type: string
        default: "5m"
    steps:
      - attach_workspace:
          at: << parameters.path >>
      - run:
          name: Terraform apply
          command: |
            TF_ARGS=""
            if [ "<< parameters.auto_approve >>" = "true" ]; then
                TF_ARGS="$TF_ARGS -auto-approve"
            fi
            envdir /secrets terraform -chdir=<< parameters.path >> apply \
              -lock-timeout=<< parameters.lock_timeout >> \
              -parallelism=<< parameters.parallelism >> \
              << parameters.out >> \
              $TF_ARGS

jobs:
  validate_and_plan:
    executor: infrastructure_container
    steps:
      - checkout
      - setup_secrets
      - terraform_init
      - terraform_validate
      - terraform_plan
  plan:
    executor: infrastructure_container
    steps:
      - checkout
      - setup_secrets
      - terraform_init
      - terraform_plan
  apply:
    executor: infrastructure_container
    steps:
      - checkout
      - setup_secrets
      - terraform_init
      - terraform_apply

workflows:
  test:
    jobs:
      - validate_and_plan:
          context: ae-infra-manage
          requires: []
          filters:
            branches:
              ignore: master

  deploy:
    jobs:
      - plan:
          context: ae-infra-manage
          requires: []
          filters:
            branches:
              only: master

      - hodl:
          type: approval
          requires: []
          filters:
            branches:
              only: master

      - apply:
          context: ae-infra-manage
          requires:
            - plan
            - hodl
          filters:
            branches:
              only: master
